
// This file has been generated by the GUI designer. Do not modify.
namespace Ideas.Scada.Server.Manager.Settings.General
{
	public partial class IdeasServer
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Ideas.Scada.Server.Manager.Settings.General.IdeasServer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Ideas.Scada.Server.Manager.Settings.General.IdeasServer";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
