
// This file has been generated by the GUI designer. Do not modify.
namespace Ideas.Scada.Server.Manager
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action EditAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action aboutAction;
		private global::Gtk.Action quitAction;
		private global::Gtk.Action openAction;
		private global::Gtk.Action quitAction1;
		private global::Gtk.Action closeAction;
		private global::Gtk.Action tbbOpen;
		private global::Gtk.Action tbbClose;
		private global::Gtk.Action tbbStartServer;
		private global::Gtk.Action tbbStopServer;
		private global::Gtk.Action SettingsAction;
		private global::Gtk.Action saveAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar3;
		private global::Gtk.Toolbar tbrMenuBar;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView trvApplicationTreeView;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView txvTextView;
		private global::Gtk.Statusbar statusbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Ideas.Scada.Server.Manager.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.EditAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.aboutAction, null);
			this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-quit");
			this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.quitAction, null);
			this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open..."), null, "gtk-open");
			this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open Application");
			w1.Add (this.openAction, null);
			this.quitAction1 = new global::Gtk.Action ("quitAction1", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-quit");
			this.quitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.quitAction1, null);
			this.closeAction = new global::Gtk.Action ("closeAction", global::Mono.Unix.Catalog.GetString ("Close"), null, "gtk-close");
			this.closeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close Application");
			w1.Add (this.closeAction, null);
			this.tbbOpen = new global::Gtk.Action ("tbbOpen", global::Mono.Unix.Catalog.GetString ("Open"), global::Mono.Unix.Catalog.GetString ("Open..."), "gtk-open");
			this.tbbOpen.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
			w1.Add (this.tbbOpen, null);
			this.tbbClose = new global::Gtk.Action ("tbbClose", global::Mono.Unix.Catalog.GetString ("Close"), global::Mono.Unix.Catalog.GetString ("Close"), "gtk-close");
			this.tbbClose.Sensitive = false;
			this.tbbClose.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
			w1.Add (this.tbbClose, null);
			this.tbbStartServer = new global::Gtk.Action ("tbbStartServer", global::Mono.Unix.Catalog.GetString ("Start"), global::Mono.Unix.Catalog.GetString ("Start Server"), "gtk-execute");
			this.tbbStartServer.Sensitive = false;
			this.tbbStartServer.ShortLabel = global::Mono.Unix.Catalog.GetString ("Start Server");
			w1.Add (this.tbbStartServer, null);
			this.tbbStopServer = new global::Gtk.Action ("tbbStopServer", global::Mono.Unix.Catalog.GetString ("Stop"), global::Mono.Unix.Catalog.GetString ("Stop Server"), "gtk-stop");
			this.tbbStopServer.Sensitive = false;
			this.tbbStopServer.ShortLabel = global::Mono.Unix.Catalog.GetString ("Stop");
			w1.Add (this.tbbStopServer, null);
			this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings..."), null, null);
			this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings...");
			w1.Add (this.SettingsAction, null);
			this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("_Save"), null, "gtk-save");
			this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Save");
			w1.Add (this.saveAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Ideas.Scada.Server.Manager.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("IDEAS Server Management");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Ideas.Scada.Server.Manager.Resources.Icons.icon_32x32.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			// Container child Ideas.Scada.Server.Manager.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><menubar name='menubar3'><menu name='FileAction' action='FileAction'><menuitem name='openAction' action='openAction'/><menuitem name='saveAction' action='saveAction'/><menuitem name='closeAction' action='closeAction'/><separator/><menuitem name='quitAction1' action='quitAction1'/></menu><menu name='EditAction' action='EditAction'><menuitem name='SettingsAction' action='SettingsAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
			this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar3")));
			this.menubar3.Name = "menubar3";
			this.vbox1.Add (this.menubar3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name=\'tbrMenuBar\'><toolitem name=\'tbbOpen\' action=\'tbbOpen\'/><toolit" +
                    "em name=\'tbbClose\' action=\'tbbClose\'/><toolitem name=\'tbbStartServer\' action=\'tb" +
                    "bStartServer\'/><toolitem name=\'tbbStopServer\' action=\'tbbStopServer\'/></toolbar>" +
                    "</ui>");
			this.tbrMenuBar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/tbrMenuBar")));
			this.tbrMenuBar.TooltipMarkup = "Start Server";
			this.tbrMenuBar.Name = "tbrMenuBar";
			this.tbrMenuBar.ShowArrow = false;
			this.tbrMenuBar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.tbrMenuBar.IconSize = ((global::Gtk.IconSize)(1));
			this.vbox1.Add (this.tbrMenuBar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.tbrMenuBar]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 276;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trvApplicationTreeView = new global::Gtk.TreeView ();
			this.trvApplicationTreeView.CanFocus = true;
			this.trvApplicationTreeView.Name = "trvApplicationTreeView";
			this.trvApplicationTreeView.HeadersVisible = false;
			this.GtkScrolledWindow.Add (this.trvApplicationTreeView);
			this.hpaned1.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
			w5.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.txvTextView = new global::Gtk.TextView ();
			this.txvTextView.CanFocus = true;
			this.txvTextView.Name = "txvTextView";
			this.GtkScrolledWindow1.Add (this.txvTextView);
			this.hpaned1.Add (this.GtkScrolledWindow1);
			this.vbox1.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
			w8.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.aboutAction.Activated += new global::System.EventHandler (this.aboutAction_Click);
			this.quitAction.Activated += new global::System.EventHandler (this.mnuFileExit_Click);
			this.openAction.Activated += new global::System.EventHandler (this.mnuOpenApplication_Click);
			this.quitAction1.Activated += new global::System.EventHandler (this.mnuFileExit_Click);
			this.closeAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
			this.tbbOpen.Activated += new global::System.EventHandler (this.tbbOpen_Click);
			this.tbbClose.Activated += new global::System.EventHandler (this.tbbClose_Click);
			this.tbbStartServer.Activated += new global::System.EventHandler (this.tbbStartServer_Click);
			this.tbbStopServer.Activated += new global::System.EventHandler (this.tbbStopServer_Click);
			this.SettingsAction.Activated += new global::System.EventHandler (this.OnSettingsActionActivated);
			this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		}
	}
}
