//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Web;
using System.Web.UI;

namespace Ideas.Scada.Server.WebApplication
{
	public partial class Default : System.Web.UI.Page
	{
		public Default()
		{
			
		}
		
	    protected override void OnLoad(EventArgs e)
	    {
			WriteData();
			base.OnLoad(e);
	    }
	
	    private void WriteData()
	    {
			//Response.ContentType = "image/png";
			Response.WriteFile(System.Configuration.ConfigurationManager.AppSettings["InitialScreen"], true);
	    }
	}
}

